version: "3"
services:
  db:
    image: mysql/mysql-server:5.7
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_USER=user"
      - "MYSQL_PASSWORD=Password@123"
      - "MYSQL_DATABASE=golang"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3306"]
      interval: 30s
      timeout: 10s
      retries: 5
  web:
    build: .
    ports:
      - "7331:7331"
    volumes:
      - ".:/app"
    depends_on:
      db:
        condition: service_healthy
    links:
      - "db:database"
